<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK3mHdcb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK3mHdcb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK3mHdcb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK3mHdcb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK3mHdcb\App_KernelDevDebugContainer([
    'container.build_hash' => 'K3mHdcb',
    'container.build_id' => '56005657',
    'container.build_time' => 1607422145,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK3mHdcb');
