<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBhuFK2K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBhuFK2K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBhuFK2K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBhuFK2K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBhuFK2K\App_KernelDevDebugContainer([
    'container.build_hash' => 'BhuFK2K',
    'container.build_id' => 'ab70fd6a',
    'container.build_time' => 1607346081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBhuFK2K');
