<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8p5OGo0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8p5OGo0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8p5OGo0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8p5OGo0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8p5OGo0\App_KernelDevDebugContainer([
    'container.build_hash' => '8p5OGo0',
    'container.build_id' => 'ce71838c',
    'container.build_time' => 1607423691,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8p5OGo0');
